// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

const peopleInfo = [
  {
    partner_id: "23",
    name: "RICHARD L. KUEI",

    title: "Partner and Principal of HBAarchitecture",
    cn_title: "",
    office: "Shanghai",
    cn_office: "",
    email: "info@hbaarchitecture.com",
    image_1: "2d9c1-01-richard-long.jpg",
    image_2: "",
    partner_office_image: "",
    bio: "Richard is an HBA Partner and Principal of HBAarchitecture and an associate member of the American Institute of Architects. He has a Bachelor’s of Architecture Degree from California State Polytechnic University, Pomona, with more ¬than twenty-five years of experience in Architecture & Commercial Mixed-Use Retail projects in the U.S., China and throughout South East Asia.\n<br><br>\nBefore joining HBAarchitecture, Richard worked in the U.S. office of Altoon Partners for over 13 years, from designer to Associate Partner and Design Director, help established a design coordination office in Shanghai, lead the company’s master planning and design efforts in commercial retail architecture throughout the region.\n<br><br>\nYears of professional training in various part of the globe allowed Richard to develop a keen understanding for the economics of commercial retail developments, as well as a unique perspective on space planning and creative solutions to enrich the overall commercial retail experience.\n<br><br>\nRichard's background and extensive traveling experience developed into a clear understanding of both Asian and western cultures, which is essential in successful international team collaborations. His knowledge of the overall project development process in China allows him to work effectively and efficiently with clients, government officials and design consultants alike, producing projects of the highest quality and success.\n<br><br>\nAs a member of the International Council of Shopping Centers, Richard has taught at the ICSC Development, Design and Construction School in Shanghai on Design Principles and Practices focusing on the Asia market.",
    cn_bio: "",
    notable_project:
      '<p><br>PROJECT HISTORY</p>\n<p>Since launching HBAarchitecture in Shanghai in August 2013, Richard secured the commission and served as the Project Director for the following Architecture projects:</p>\n<ul>\n\t<li>Chongqing Centre Mixed-use <span class="ph-city">Chongqing China</span></li>\n\t<li>Grace-land Mixed-use <span class="ph-city">Yibin, China</span></li>\n\t<li>Powerlong Commercial Retail <span class="ph-city">Jiaozhou, China</span></li>\n\t<li>CYE Cultural Plaza <span class="ph-city">Hangzhou, China</span></li>\n\t<li>Xuhui Lifestyle Mall <span class="ph-city">Shanghai, China</span></li>\n\t<li>Waterfront Retail Baku <span class="ph-city">Azerbaijan, Baku</span></li>\n</ul>\n<p>Prior to joining HBAarchitecture, Richard worked at Altoon Partners for over thirteen years. From 2007 to 2013, Richard was Associate Partner of the firm’s Shanghai office. While managing the operation of the Shanghai office, he served as the Project Director, planner and designer on the following retail commercial projects:</p>\n<p><br>MIXED-USE & COMMERCIAL RETAIL</p>\n<ul>\n\t<li>Walsin Centro Mixed-use <span class="ph-city">Nanjing, China</span></li>\n\t<li>Shimao Wuhan Carnival Mixed-use <span class="ph-city">Wuhan, China </span></li>\n\t<li>GTLand Pearl River F2-4 Planning <span class="ph-city">Guangzhou, China </span></li>\n\t<li>Walsin Village Retail Promenade <span class="ph-city">Nanjing, China </span></li>\n\t<li>Taiwan Trade Mart Promenade <span class="ph-city">Nanjing, China</span></li>\n\t<li>Far Eastern Department Store <span class="ph-city">Taichung, Taiwan </span></li>\n\t<li>Paragon Guangzhou Sun City Mall <span class="ph-city">Guangzhou, China </span></li>\n\t<li>Chongbang Jiading Mixed-use <span class="ph-city">Shanghai, China</span></li>\n\t<li>Xi’an Qujiang Daming Place <span class="ph-city">Xi’an, China </span></li>\n\t<li>CDG Tianjin Mixed-use Retail <span class="ph-city">Tiangjin, China </span></li>\n\t<li>Dosun Taizhou Mixed-use <span class="ph-city">Taizhou, China </span></li>\n\t<li>Dosun Hangzhou Commercial <span class="ph-city">Hangzhou, China</span></li>\n\t<li>E. Coast Shunde Lifestyle Village <span class="ph-city">Guangzhou, China</span></li>\n\t<li>Marina City Qingdao Retail Centre <span class="ph-city">Qingdao, China</span></li>\n\t<li>Jiading Bao an Lu Retail Centre <span class="ph-city">Jiading, China</span></li>\n\t<li>Loncin Golf Resort Village <span class="ph-city">Chongqing, China</span></li>\n\t<li>GTLand Lifestyle Olympic Centre <span class="ph-city">Guangzhou, China</span></li>\n\t<li>Golden Eagle Suzhou <span class="ph-city">Suzhou, China</span></li>\n\t<li>Paragon Pearl River Sun City Mall <span class="ph-city">Guangzhou, China</span></li>\n\t<li>CYE Cultural Plaza Retail Interior <span class="ph-city">Ningbo, China</span></li>\n\t<li>Wenzhou World trade interiors <span class="ph-city">Wenzhou, China</span></li>\n</ul><br>\n<p>Before relocating to Shanghai, Richard was a senior Associate in the Los Angeles Office of Altoon Partners and worked as a Senior Planner and Designer on following Architecture projects from 1999 to 2007:</p>\n<p>\n\t </p>\n<ul>\n\t<li>The Gardens on El Paseo Retail Palm Desert <span class="ph-city">California, USA</span></li>\n\t<li>Dubai Festival City Power Centre <span class="ph-city">Dubai, UAE</span></li>\n\t<li>Mall at Kashirskoye-Shosse <span class="ph-city">Moscow, Russia</span></li>\n\t<li>Victoria Gardens Retail Centre R. Cucamonga <span class="ph-city">California, USA</span></li>\n\t<li>The Shops at Tanforan San Bruno <span class="ph-city">California, USA </span></li>\n\t<li>Adriatico Towers and Retail <span class="ph-city">Manila, Philippines </span></li>\n\t<li>Yasenevo Commercial Retail <span class="ph-city">Moscow, Russia </span></li>\n\t<li>Zhong Guan Village int’l School <span class="ph-city">Beijing, China</span></li>\n\t<li>Elk Grove Village Shopping Centre Elk Grove <span class="ph-city">California, USA</span></li>\n\t<li>Kowloon Station Retail Planning <span class="ph-city">Hong Kong</span></li>\n\t<li>Marina Square Shopping Centre <span class="ph-city">Singapore</span></li>\n</ul>',
    cn_notable_project: "",
    notable_awards: "",
    cn_notable_awards: "",
    language: "English",
    cn_language: "",
    from: null,
    display_order: "1",
    is_active: "1",
  },
  {
    partner_id: "24",
    name: "DONGMIN SHIM",

    title: "Director of Architecture",
    cn_title: "",
    office: "Singapore",
    cn_office: "",
    email: "info@hbaarchitecture.com",
    image_1: "9963e-01-dongmin-long.jpg",
    image_2: "",
    partner_office_image: "",
    bio: "As the Director of the Singapore architecture studio, Dongmin focuses on delivering iconic destinations and helping Clients realize the full potential of their investments. With a background in economics and architecture degree from Harvard University, Dongmin brings a unique perspective to architecture that combines innovative, experiential design with strategic thinking and deep understanding of how market forces and technology are shaping our lives.\n<br><br>\nPrior to joining HBA, Dongmin was the Design Principal at award-winning WOW Architects in Singapore, leading the studio on a number of iconic hospitality and mixed-use projects throughout Asia, including the Mega Kuningan Mixed-Use Development in Jakarta, Anantara Resort and Residence in Desaru Coast and Bhartiya City South in Bangalore, India.\n<br><br>\nDongmin’s hospitality experience includes all aspects of hotel planning and development, from feasibility and master planning to back-of-house planning and construction supervision to developing new products and brands for operators like IHG. His track record has landed his studio on a number of recommended lists for international operators including Hilton and Anantara.\n<br><br>\nA native of Seoul, Korea, Dongmin grew up in the U.S. and later received his bachelor’s degree in Economics from Stanford University. Following college, he was a Graphics Editor for the New York Times and Newsweek Magazine. After graduating from Harvard University with his Master in Architecture, Dongmin worked for a number of world-renowned firms including AECOM, where he was an Associate Design Director and Spark Architects in Beijing.",
    cn_bio: "",
    notable_project:
      '<p><br>\n\tPROJECT HISTORY (WOW Architects)<br /><br />\n\tHOSPITALITY</p>\n<ul>\n\t<li>Hilton Jakarta Hotel & Residence <span class="ph-city">Jakarta, Indonesia</span></li>\n\t\t<li>Anantara Resort Desaru <span class="ph-city">Desaru, Malaysia</span></li>\n\t\t<li>Hilton Hai Phong <span class="ph-city">Hai Phong, Vietnam</span></li>\n\t\t<li>Manado Eco Resort <span class="ph-city">Manado, Indonesia</span></li>\n\t\t<li>Ubud Botanical Resort <span class="ph-city">Bali, Indonesia</span></li>\n\t\t<li>Leela Hotel & Residence <span class="ph-city">Bangalore, India</span></li>\n\t\t<li>Hilton Garden Inn <span class="ph-city">Karawang, Indonesia</span></li>\n\t\t<li>Vivanta by Taj Service Apartment <span class="ph-city">Gurgaon, India</span></li>\n</ul>\n<p>\n\t </p>\n<p>HOSPITALITY CONTD.</p>\n<ul>\n\t<li>Hualuxe Resort Brand Standards <span class="ph-city">Shanghai, China</span></li>\n\t\t<li>Manila Bay Hotel & Mall Master Plan <span class="ph-city">Manila, Philippines</span></li>\n\t\t<li>Eaton Luxe Resort <span class="ph-city">Bali, Indonesia</span></li>\n\t\t<li>Courtyard by Marriott <span class="ph-city">Jakarta, Indonesia</span></li>\n\t\t<li>Four Points by Sheraton <span class="ph-city">Faridabad, India</span></li>\n</ul>\n<p>\n\t </p>\n<p>MIXED-USE & RESIDENTIAL</p>\n<ul>\n\t<li>Bhartiya CityCentre Mall <span class="ph-city">Bangalore, India</span></li>\n\t\t<li>Nikoo Homes 2 <span class="ph-city">Bangalore, India</span></li>\n\t\t<li>Bhartiya City Urban Resort <span class="ph-city">Bangalore, India</span></li>\n\t\t<li>Tata Square <span class="ph-city">Gurgaon, India</span></li>\n\t\t<li>Paras Square <span class="ph-city">Gurgaon, India</span></li>\n\t\t<li>Sultanpur Farmhouse <span class="ph-city">New Delhi, India</span></li>\n\t\t<li>Sohna Road Residential <span class="ph-city">Gurgaon, India</span></li>\n\t\t<li>Meg Kuningan Mixed-Use <span class="ph-city">Jakarta, India</span></li>\n\t\t<li>Chongqing Mixed Use <span class="ph-city">Chongqing, China</span></li>\n\t\t<li>Wanda Fuzhou Mixed Use <span class="ph-city">Fuzhou, China</span></li>\n</ul>',
    cn_notable_project: "",
    notable_awards: "",
    cn_notable_awards: "",
    language: "English",
    cn_language: "",
    from: null,
    display_order: "3",
    is_active: "1",
  },
  {
    partner_id: "25",
    name: "JOE LAU",

    title: "Design Director",
    cn_title: "",
    office: "Shanghai",
    cn_office: "",
    email: "info@hbaarchitecture.com",
    image_1: "f257f-03-joe-long.jpg",
    image_2: "",
    partner_office_image: "",
    bio: "Joe Lau is an Australian Registered Architect with Bachelor degrees in Design Studies and Architecture from the University of Queensland, Australia.\n<br><br>\nJoe has over 20 years’ experience in the fields of Architectural Design, Urban Design and Master Planning. He has been credited with the conception of master plans and concept designs for numerous largescale residential and resort developments throughout Australia and Asia. He is passionate about the preservation of indigenous cultural and natural environment of the project sites, resulting in in design outcome which is a harmonious fusion of the natural and built environment with a unique sense of place.\n<br><br>\nHis interest in macro scaled projects led him to focus on master planning and urban design where has honed his expertise over the years. He has implemented innovative and site responsive designs that have enabled clients to exceed the outcomes they envisaged at the start of the project. His goal with each project is to deliver maximum outcome for the client and to create outstanding built environments for the end users whilst ensuring environmental sustainability.",
    cn_bio: "",
    notable_project:
      '<p>PROJECT HISTORY</p>\n<ul>\n<li>Xinchang Chedi Resort Hotel <span class="ph-city">Xhejiang, China </span></li>\n<li>Genting Highland Hotel <span class="ph-city">Pahang Darul Makmur, Malaysia </span></li>\n<li>Emma Lagoon Resort <span class="ph-city">South Male Atoll, Maldives </span></li>\n<li>Dali Eryuan Cultural Resort Hotel <span class="ph-city">Yunnan, China </span></li>\n<li>Gamuda HH2 Residential <span class="ph-city">Hanoi, Vietnam </span></li>\n<li>Yueyang Resort Hotel <span class="ph-city">Hunan, China </span></li>\n</ul>\n<p>Prior to joining HBAarchitecture, Joe worked as the Partner and Design Director of ANS Architects and Planners. He led his team to win over 10 urban design and architectural design competitions. His team’s more notable project is the winning design of the 16 Pier passenger ferry terminal in Shanghai. Joe has been involved in projects that cover a substantial part of the Asia Pacific region. His fluency in 7 languages of the region is an invaluable asset to any team. </p>\n\n<p>Before joining ANS, Joe was an executive design architect with internationally recognized gold coast based Australian design firm, DBI Design where he was a key designer responsible for the BOAO Asia Forum’s Conference and Conventional facilities and then Sofitel Hotel. Joe was also the chief designer of a chain of Sea Temple Spa resorts along the east coast of Australia</p>\n<br>\n<p>MASTER PLAN </p>\n<ul>\n<li>16 Pier, Bund <span class="ph-city">Shanghai, China </span></li>\n<li>Hengshan Island Master Plan <span class="ph-city">Zhuhai, China </span></li>\n<li>Tianjin Binhai Urban Renewal <span class="ph-city">Tianjin, China</span></li>\n<li>Binzhou Creative Industry Satellite City <span class="ph-city">Shandong, China </span></li>\n<li>Wuhan Eco Link <span class="ph-city">Hubei, China </span></li>\n</ul>\n<br>\n<p>HOSPITALITY </p>\n<ul>\n<li>Jixian Marriott Resort <span class="ph-city">Tianjin, China </span></li>\n<li>Natadola Intercontinental Hotel <span class="ph-city">Fiji </span></li>\n<li>BOAO Asia Forum International Conference Center <span class="ph-city">Hainan, China </span></li>\n<li>Sea Temple <span class="ph-city">Port Douglas, Australia </span></li>\n<li>Sea Temple, <span class="ph-city">Palm Cove Australia </span></li>\n<li>Nanzhi Island Resort <span class="ph-city">Hainan, China </span></li>\n<li>Taoxi Mushroom-themed Resort <span class="ph-city">Fujian, China </span></li>\n</ul>',
    cn_notable_project: "",
    notable_awards: "",
    cn_notable_awards: "",
    language: "English",
    cn_language: "",
    from: null,
    display_order: "2",
    is_active: "1",
  },
  {
    partner_id: "26",
    name: "LASSE WAGER",

    title: "Design Director",
    cn_title: "",
    office: "Shanghai",
    cn_office: "",
    email: "info@hbaarchitecture.com",
    image_1: "26093-04a-lasse-wager.jpg",
    image_2: "",
    partner_office_image: "",
    bio: "Lasse Wager is a Design Director and a licensed architect in Finland with over 21 years of experience as the Head Designer and Head Architect in various large scale projects. As a core leader of the HBAarchitecture Shanghai office, Mr. Wager is specialized in designing major complex large scale commercial mixed-use, retail and hospitality projects and leading the design teams in order to develop the design and to meet the design and developmental goals of the project and the client during Concept Design, Schematic Design and Design Development phases.\n\nBefore joining HBAarchitecture, Mr. Wager worked as a Design Director in IBI Group, AUD Architects in Los Angeles and Shanghai, Ocean North in London and UDG with PES Architects, Helin & Co and 3XN in Shanghai on a number of commissions throughout United States, Canada, Europe and China. Mr. Wager holds a Master Degree from the University of Oulu in Finland.\n\nDuring his career, his work has been shown in exhibitions and widely published in magazines and books including The New York Times, DOMUS, Italy; DETAIL Germany; AD Architectural Design, London; 10x10 Architects, London; Hybrid Space, London; Archiworld, Seoul; De Architect, Netherlands and Finnish Architectural Review.",
    cn_bio: "",
    notable_project:
      "<p>MIXED-USE</p>\n<ul>\n\t<li>Nangang Office Building, Taipei, Taiwan</li>\n\t<li>\n\t\tSunac Headquarter Towers, Beijing, China</li>\n\t<li>\n\t\tEl Paso Tower, El Paso, Texas, U.S.A.</li>\n\t<li>\n\t\tCultural Industry Building, Marriott Courtyard, Zhengzhou, China</li>\n\t<li>\n\t\tTower Sainte Catherine & De Bleury Mixed-use, Montreal, Canada</li>\n\t<li>\n\t\tOgilvie Mall and Hotel, Montreal, Canada </li>\n\t<li>\n\t\tYurun Plaza Mixed-use, Daye, China</li>\n\t<li>\n\t\tAbu Dhabi High-Rise complex CBD, Al Reem Island, Abu Dhabi, U.A.E</li>\n\t<li>\n\t\tTiancheng Commercial Complex, Changsha, China</li>\n\t<li>\n\t\tZhengzhou Zhongjian CBD, Zhengzhou, China</li>\n\t<li>\n\t\tChina Unicom Headquarters, Shenyang, China</li>\n\t<li>\n\t\tLangfang Grand Theatre, Langfang, China</li>\n\t<li>\n\t\tChengdu Xinglonghu Mixed-Use,  Chengdu, China</li>\n\t<li>\n\t\tVanke Mixed-Use, Suzhou, China</li>\n\t<li>\n\t\tHuiyi Cultural Industry Building, Zhengzhou, China</li>\n\t<li>\n\t\tZhengjiang Center, Zhengjiang, China</li>\n\t<li>\n\t\tSunac Qingdao Mixed-use, Qingdao, China</li>\n\t<li>\n\t\t   </li>\n</ul>\n<p>HOSPITALITY</p>\n<ul>\n\t<li>\n\t\tSunac Qingdao Mixed-use,</li>\n\t<li>\n\t\tKempinski Hotel, Qingdao, China </li>\n\t<li>\n\t\tChengdu Xinglonghu Hilton Double Tree, Chengdu, China</li>\n\t<li>\n\t\tTanshan Sheraton hotel, Tangshan, China</li>\n\t<li>\n\t\tMarriott Resort, Sanya, China</li>\n\t<li>\n\t\tVirkatie Center Marriott Hotel, Helsinki, Finland</li>\n\t<li>\n\t\tVanke Ascott Hotel, Suzhou, China</li>\n\t\n</ul>\n",
    cn_notable_project: "",
    notable_awards: "",
    cn_notable_awards: "",
    language: "English",
    cn_language: "",
    from: null,
    display_order: "4",
    is_active: "1",
  },
  {
    partner_id: "27",
    name: "HOWARD TSENG",

    title: "Director",
    cn_title: "",
    office: "Shanghai",
    cn_office: "",
    email: "howard.tseng@hbaarchitecture.com",
    image_1: "be955-howard-tseng.jpg",
    image_2: "",
    partner_office_image: "",
    bio: "Howard works within the leadership team on business operations, and the management and development of the Shanghai Office. \r\n<br><br>\r\nPrior to HBAarchitecture, Howard serves as China representative and executive director of architecture and interior projects for award-winning studio Nendo INC and Design Director at Walsin Real Estate Development.\r\n",
    cn_bio: "",
    notable_project: null,
    cn_notable_project: "",
    notable_awards: "",
    cn_notable_awards: "",
    language: "English",
    cn_language: "",
    from: null,
    display_order: "4",
    is_active: "1",
  },
  {
    partner_id: "28",
    name: "ATSUSHI KUBOTA",

    title: "Senior Associate",
    cn_title: "",
    office: "Shanghai",
    cn_office: "",
    email: "atsushi.kubota@hbaarchitecture.com",
    image_1: "42963-atsushi-kubota.jpg",
    image_2: "",
    partner_office_image: "",
    bio: "Atsushi has over 15 years industry experience in architecture and Master planning design, having worked for several award-winning firms across Australia. He has contributed to a diverse collection of projects ranging from multiple high-rise, residential developments, to large scale master planning projects, a winery, art gallery, luxury private homes, bars and restaurants and hotels. With a broad experience in architecture and hospitality and with his multi-cultural background and multiple language skills he is a prime candidate for complex international projects.",
    cn_bio: "",
    notable_project: null,
    cn_notable_project: "",
    notable_awards: "",
    cn_notable_awards: "",
    language: "English",
    cn_language: "",
    from: null,
    display_order: "5",
    is_active: "1",
  },
  {
    partner_id: "29",
    name: "YICHIEH SU",

    title: "Senior Associate",
    cn_title: "",
    office: "Shanghai",
    cn_office: "",
    email: "yichieh.su@hbaarchitecture.com",
    image_1: "00b03-yichieh-su.jpg",
    image_2: "",
    partner_office_image: "",
    bio: "Yi-Chieh is an architecture designer with the background of both architecture and urban design. She has rich experience in architecture design, TOD mixed-use planning design, urban public facility design and culture & art architecture design over the past 20 years. \r\nShe has successful projects in China main land, Taiwan and has been awarded for many prizes. Yi-Chieh has a bachelor degree in architecture of Tunghai University and master in urban strategy of University of Applied Sciences Technikum Wien.",
    cn_bio: "",
    notable_project: null,
    cn_notable_project: "",
    notable_awards: "",
    cn_notable_awards: "",
    language: "English",
    cn_language: "",
    from: null,
    display_order: "6",
    is_active: "1",
  },
];

export default function handler(req, res) {
  if (req.method === "POST") {
    console.log(req.body.partner_id);
    const returnable = peopleInfo.find(
      (item) => item.partner_id == req.body.partner_id
    );
    res.status(200).json(returnable);
  } else {
    peopleInfo.sort((a, b) => {
      return a.display_order - b.display_order;
    });
    res.status(200).json(peopleInfo);
  }
}
